In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
df=pd.read_csv("//content/healthcare-dataset-stroke-data.csv")

In [3]:
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [4]:
df.corr()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
id,1.000000,0.003538,0.003550,-0.001296,0.001092,0.003084,0.006388
age,0.003538,1.000000,0.276398,0.263796,0.238171,0.333398,0.245257
hypertension,0.003550,0.276398,1.000000,0.108306,0.174474,0.167811,0.127904
heart_disease,-0.001296,0.263796,0.108306,1.000000,0.161857,0.041357,0.134914
avg_glucose_level,0.001092,0.238171,0.174474,0.161857,1.000000,0.175502,0.131945
bmi,0.003084,0.333398,0.167811,0.041357,0.175502,1.000000,0.042374
stroke,0.006388,0.245257,0.127904,0.134914,0.131945,0.042374,1.000000

In [5]:
df_score=df.drop(columns=["ever_married","work_type","Residence_type","smoking_status"])

In [6]:
df_score.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [8]:
mean_value=df_score['bmi'].mean()

In [9]:
df_score['bmi'].fillna(value=mean_value,inplace=True)

In [10]:
df_score

,id,gender,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
0,9046,Male,67.0,0,1,228.69,36.600000,1
1,51676,Female,61.0,0,0,202.21,28.893237,1
2,31112,Male,80.0,0,1,105.92,32.500000,1
3,60182,Female,49.0,0,0,171.23,34.400000,1
4,1665,Female,79.0,1,0,174.12,24.000000,1
...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,83.75,28.893237,0
5106,44873,Female,81.0,0,0,125.20,40.000000,0
5107,19723,Female,35.0,0,0,82.99,30.600000,0
5108,37544,Male,51.0,0,0,166.29,25.600000,0
5109,44679,Female,44.0,0,0,85.28,26.200000,0

In [11]:
# splitting the data in x and y that is input and output
x=df_score.iloc[:,2:11]
y=df_score['stroke'].values

In [12]:
x

       age  hypertension  heart_disease  avg_glucose_level        bmi  stroke
0     67.0             0              1             228.69  36.600000       1
1     61.0             0              0             202.21  28.893237       1
2     80.0             0              1             105.92  32.500000       1
3     49.0             0              0             171.23  34.400000       1
4     79.0             1              0             174.12  24.000000       1
...    ...           ...            ...                ...        ...     ...
5105  80.0             1              0              83.75  28.893237       0
5106  81.0             0              0             125.20  40.000000       0
5107  35.0             0              0              82.99  30.600000       0
5108  51.0             0              0             166.29  25.600000       0
5109  44.0             0              0              85.28  26.200000       0

[5110 rows x 6 columns]

In [13]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [14]:
# splitting the data into train and test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
# an initial SVM model with linear kernel
clf=SVC(kernel="linear",random_state=0)

In [16]:
# fill the model
clf.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [17]:
# fit the model
clf.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [18]:
# now our model is ready so we can predict tje values
pred_y=clf.predict(x_test)

In [19]:
pred_y=clf.predict(x_test)

In [20]:
pred_y

array([1, 0, 0, ..., 0, 1, 0])

In [21]:
y_test

array([1, 0, 0, ..., 0, 1, 0])

In [23]:
# the confusion matrix is a summary of prediction results of a given classification problem
confusion_matrix(y_test,pred_y)

array([[968,   0],
       [  0,  54]])

In [24]:
accuracy=accuracy_score(y_test,pred_y)

In [25]:
accuracy

1.0

In [26]:
print("accuracy=",accuracy*100,"%")

accuracy= 100.0 %